[package]
name = "frontend-sdl"
version = "0.1.0"
authors = ["TomasKralCZ <tomas@kral.hk>"]
default-run = "frontend-sdl"

[dependencies]
fearless_nes = { path = "../nes" }
sdl2 = "0.33.0"
clap = "2.33.0"
rand = "0.7.3"
