[package]
name = "frontend-sdl"
version = "0.1.0"
authors = ["TomasKralCZ <tomas@kral.hk>"]
edition = "2018"
default-run = "frontend-sdl"

[dependencies]
fearless_nes = { path = "../nes" }
clap = "2.33.0"
sdl2 = "0.34.0"
